name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Criar arquivo .env com DATABASE_URL
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      
      - name: Aplicar migrações do Prisma
        run: npx prisma migrate deploy
        
      - name: Rodar os testes vitest    
        run: npm run test    

      

